### ISSUE TITLE
Enable highlight for Jenkinse CI console output

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/jenkins-pipeline-scripts#10]
**Problem:**
Now it's very hard to work with the Jenkinse log, because no all messages with any severity don't highlighted, and this increase complexity of  log analyse.
![image](https://user-images.githubusercontent.com/7566324/50821267-76df8580-1337-11e9-967d-0095bc86fd1b.png)

**Comment by krankenbro** [comment]
![6dotvfze77](https://user-images.githubusercontent.com/42555001/52469819-302eb680-2b95-11e9-9c2a-c73d4b634d75.gif)
Added Log Parser Plugin. Now we have: 
1. log navigation
2. log highlight

**Comment by tatarincev** [comment]
![image](https://user-images.githubusercontent.com/7566324/53327063-b2d2a800-38ef-11e9-9d21-9a51cd5ac430.png)

Seems it isn't installed on https://ci.virtocommerce.com

**Comment by krankenbro** [comment]
Probably it was hidden because of user role bug. Now it's ok. 
![microsoftteams-image](https://user-images.githubusercontent.com/42555001/53343274-aca4f180-3918-11e9-80fa-9e00b7c8b736.png)
