### ISSUE TITLE
Establish the delivery  of themes changes to the demo.virtocommerce.com

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/jenkins-pipeline-scripts#11]
**Problem**
All changes with these themes (https://github.com/VirtoCommerce/vc-theme-default, https://github.com/VirtoCommerce/vc-theme-b2b, https://github.com/VirtoCommerce/vc-theme-material) get on production only with sample data, it is the manual process that takes a more time. 

**Solution**
Need to establish deployment process of all theme releases into demo.virtocommerce.com after successfully passed CI

**Comment by krankenbro** [comment]
There were merged 3 jenkins jobs for update platform, storefront, db for demo.virtocommerce.com. And added the step for getting the latest themes releases from github and deploy to demo.virtocommerce.com
