### ISSUE TITLE
Change the default branch to dev for all Platform repositories

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/jenkins-pipeline-scripts#12]

**Comment by asvishnyakov** [comment]
Why?! Then our customers by default will download code from unstable dev branch by default, instead of stable master.

**Comment by dimitri-ak** [comment]
Done for most of the repositories.

**Comment by yecli** [comment]
Probably after that change "Deploy to Azure" button in [platform](https://github.com/VirtoCommerce/vc-platform) and [storefront](https://github.com/VirtoCommerce/vc-platform) repos by default goes to dev branch, which is indeed could be unstable, as @asvishnyakov mentioned.
Need to handle such situation somehow, as we are getting support requests regarding this:
[Gitter February 16, 2019 6:03 PM](https://gitter.im/VirtoCommerce/vc-platform?at=5c680a33604f233ab61d51e2)

**Comment by SupportMgr** [comment]
I confirm we have started getting requests from customers like "storefront new install doesn't load at all. can you help?" and they have dev branch reference. What are the reasons behind this decision?

**Comment by yecli** [comment]
I think for inner development processes: merging, CI/CD, we want to use dev branch.
But as changing repository default branch leads to user problems, probably we need to set desired branch in our inner processes explicitly and leave master as default repository branch.
