### ISSUE TITLE
Cannot bulid .NET Core 2.2 projects

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/jenkins-pipeline-scripts#15]
**Problem:**
CI cannot build the solution targeting .NET Core 2.2: [example branch](https://github.com/VirtoCommerce/vc-storefront-core/tree/feature/202-swagger-doc-generation).

Error:
The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2.

Current msbuild version: "Microsoft (R) Build Engine version 15.7.179.6572 for .NET Framework". 

**Proposed changes:**
Install [.NET Core SDK 2.2](https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-2.2.103-windows-x64-installer).

**Comment by krankenbro** [comment]
Fixed

**Comment by yecli** [comment]
Problem solved, thanks.
