### ISSUE TITLE
Jenkins scripts does not escape quotes in strings passed to github-release

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/jenkins-pipeline-scripts#6]
This function: https://github.com/VirtoCommerce/jenkins-pipeline-scripts/blob/master/src/jobs/scripts/Utilities.groovy#L74 take release notes from .NET Core project and tries to pass it to github-release, but does not escape quotes in this string, so you may get construction like this:
`github-release release --user VirtoCommerce --repo vc-storefront-core --tag v3.0.3 --description "[PRE-RELEASE]<br>- Load a user-defined  settings from the special section.<br>- Correct display of the "Access Denied" page"`
Here we have "[PRE-RELEASE] ... display of the "Access Denied" page".
Look at http://ci.virtocommerce.com/blue/organizations/jenkins/vc-2-org%2Fvc-storefront-core/detail/master/66/pipeline for details.

**Comment by krankenbro** [comment]
Added quotes escaping in [commit](https://github.com/VirtoCommerce/jenkins-pipeline-scripts/commit/100c8c8338f4c09402f9cf38cfafb3c94bc462d6)
