### ISSUE TITLE
SQL Server connection string is wrong or server is unavailable

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/jenkins-pipeline-scripts#7]
https://github.com/VirtoCommerce/jenkins-pipeline-scripts/blob/master/src/jobs/scripts/Modules.groovy#L64
`VIRTO_CONN_STR_VirtoCommerce=Data Source=http://ci.virtocommerce.com:${sqlPort};Initial Catalog=VirtoCommerce2;Persist Security Info=True;User ID=sa;Password=v!rto_Labs!;MultipleActiveResultSets=True;Connect Timeout=30`

http://ci.virtocommerce.com:1433 (34, 35, etc...) is not available. SQL Server Management Studio can't connect to it as well as VirtoCommerce module integration tests.

**Comment by krankenbro** [comment]
In sql management studio need to use comma instead of colon (http://ci.virtocommerce.com,1433)

**Comment by asvishnyakov** [comment]
@krankenbro What about integration tests?

**Comment by krankenbro** [comment]
There is no integration tests which failing now
