### ISSUE TITLE
Integrate Quality gate in the current platform CI

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/jenkins-pipeline-scripts#9]
Need to execute all E2E tests taken from https://github.com/VirtoCommerce/vc-platform-qg on the temporary environment (Docker) for each commit in master/ dev branches of  all observed repositories.

**Comment by dimitri-ak** [comment]
Waiting on test preparation.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for a long time
You may reopen this issue if it has been closed in error.
